fix: write EOF
koishijs/koishi-plugin-ffmpeg pull request #6
Opened 2023-12-31 04:30 UTC by idanran

Referenced https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/4e02d12573052c00ac4becee17e40580e855d308/lib/ffprobe.js#L160

2024-01-05 13:19 UTC, Anillc requested changes

2024-01-05 13:19 UTC, Anillc commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
这三种情况下应该 resolve 吧

2024-01-05 13:32 UTC, idanran commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
> 这三种情况下应该 resolve 吧

resolve 什么东西呢

2024-01-06 07:27 UTC, idanran commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
> 这三种情况下应该 resolve 吧

node-fluent-ffmpeg 是选择忽略的
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/4e02d12573052c00ac4becee17e40580e855d308/lib/ffprobe.js#L160

2024-01-22 08:55 UTC, Anillc commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
这个是忽略过后还会有 `close` 事件的对吧

2024-01-22 09:07 UTC, idanran commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
忽略报错

2024-01-22 09:30 UTC, Anillc commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
我知道忽略，但是忽略过后还有没有 `close` 事件，要是没有就忽略了没有 `close` 的话这个 `promise` 不就永远不会结束。所以希望你确认一下，这几个事件的时候应该忽略还是 `reject`

2024-01-22 09:37 UTC, idanran commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
低些不是有个 end 事件吗

2024-01-22 09:48 UTC, Anillc commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
哎我去，原来是 `stdin`, 那你改成忽略吧，其他情况 `reject`

2024-01-22 09:55 UTC, idanran commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
![image](https://github.com/koishijs/koishi-plugin-ffmpeg/assets/96647698/a898d123-aa9c-429c-bfb5-4b3baffb37a3)
那边说这些错误会在完成时抛出。

2024-01-22 10:21 UTC, idanran commented on src/ffmpeg.ts
> +          if (!['ECONNRESET', 'EPIPE', 'EOF'].includes(err.code)) reject(err)
> 哎我去，原来是 `stdin`, 那你改成忽略吧，其他情况 `reject`

喵

2024-01-22 11:50 UTC, Anillc approved these changes

2024-01-22 11:50 UTC, merged